// Content for the intra (staff) Help & How-To guide. Kept as data so the Help page can render,
// filter (search), and deep-link to each section. Screenshots live in public/help/intra and are
// (re)generated by e2e/capture-help.spec.js (`npm run capture:help`).

const IMG = `${process.env.PUBLIC_URL}/help/intra`;

const helpSections = [
  {
    id: 'overview',
    title: 'Getting started',
    tagline: 'The permit processing workspace',
    intro:
      'The staff portal is where Public Works reviews incoming well-permit applications, verifies payment readiness, applies permit conditions, schedules inspections, and issues permits. Use the sidebar on the left to move between the work queues, Search, Inspections, Reports, and Code Maintenance. This guide walks through each area with screenshots.',
    steps: [
      {
        title: 'The dashboard',
        image: 'home-01-dashboard.png',
        alt: 'Permit processing dashboard with work-queue count boxes and shortcut panels',
        description: 'The home dashboard is your launch pad for daily processing.',
        instructions: [
          'The Work Queues boxes show a live count for each processing stage — click a box to open that prefiltered list.',
          'The shortcut panels below jump to Search, Reports, Inspections, and Code Maintenance.',
          'The left sidebar is always available: expand Processing, Search, or Inspections to reach every screen.',
          'Click the logo or “Home” at any time to return here.',
        ],
      },
    ],
  },
  {
    id: 'queues',
    title: 'Work queues',
    tagline: 'Prefiltered application lists (Processing menu)',
    intro:
      'The Processing group in the sidebar holds four work queues — each a prefiltered list of applications at one stage of the workflow: Pending Applications, Pending Sitemaps, Approved Permits, and Failed Payments. Open a queue from the dashboard boxes or the Processing group. Every queue shares the same layout: filter fields, a sortable/paged results table, and an Open link on each row.',
    cta: { to: '/queue/PEND', label: 'Open Pending Applications' },
    steps: [
      {
        title: 'Pending Applications',
        anchor: 'queue-pending',
        image: 'queue-01-pending.png',
        alt: 'Pending Applications queue with a filter form and a results table',
        description:
          'Purpose: the main review queue — newly submitted applications awaiting staff review, permit conditions, and approval. This is where day-to-day processing starts.',
        instructions: [
          'Use the filter fields (business, last / first name, application ID, email) and click Refresh to narrow the list.',
          'Click any column header to sort; use the pager at the bottom for large lists.',
          'Click Open on a row to go to that application’s detail page and work the Approval wizard.',
          'The Status pill shows where each application stands in the workflow.',
        ],
      },
      {
        title: 'Applications Pending Sitemaps',
        anchor: 'queue-pends',
        image: 'queue-02-pends.png',
        alt: 'Pending Sitemaps queue listing applications waiting on a site-map upload',
        description:
          'Purpose: applications that have cleared review but still need a site-map file before a permit can be issued (status “Pending Sitemap”).',
        instructions: [
          'Filter and Refresh the same way as the Pending queue.',
          'Click Open to go to the detail page, then upload the site map in the Approval wizard’s Sitemap step.',
          'Once the site map is received the application moves on to the approval steps.',
        ],
      },
      {
        title: 'Approved Permits',
        anchor: 'queue-approved',
        image: 'queue-03-apprv.png',
        alt: 'Approved Permits queue with an added Permit # and approved-date range filter',
        description:
          'Purpose: approved and paid permits — the source list for looking up and reprinting issued permits.',
        instructions: [
          'This queue adds a Permit # field and an Approved Date From / To range to the standard filters.',
          'Refresh to list matching permits; each row shows the green “Approved” status pill.',
          'Click Open to view the application and preview or reprint the issued permit.',
        ],
      },
      {
        title: 'Failed Payments List',
        anchor: 'queue-failed',
        image: 'queue-04-payfl.png',
        alt: 'Failed Payments queue listing applications whose card authorization failed',
        description:
          'Purpose: applications whose credit-card vault / authorization failed and need staff follow-up (status “Payment Failed”).',
        instructions: [
          'Filter and Refresh to find the affected application.',
          'Click Open, then use the Payment section on the detail page to update the payment method or re-vault the card and retry.',
        ],
      },
    ],
  },
  {
    id: 'detail',
    title: 'Review & approve an application',
    tagline: 'The application detail page',
    intro:
      'The detail page brings the whole application together — applicant, project, wells, and payment — and hosts the guided Approval wizard. This is where most processing happens.',
    steps: [
      {
        title: 'Read the application',
        image: 'detail-01-review.png',
        alt: 'Application detail page showing the header summary, approval wizard, and project sections',
        description: 'Everything you need to process the application is on one page.',
        instructions: [
          'The header shows the Application ID, submission date, status, and the fee/total.',
          'Use the action buttons to upload documents, add notes, preview or reprint the permit, and (when allowed) cancel the application.',
          'Scroll down for the Project, Payment, and Wells sections — each can be expanded and edited.',
        ],
      },
      {
        title: 'Work the Approval wizard',
        image: 'detail-02-approval.png',
        alt: 'Approval wizard with steps for sitemap, conditions, payment, site visit, and inspections',
        description: 'The wizard walks you through every gate before a permit is issued.',
        instructions: [
          'Sitemap — confirm the required site map has been received.',
          'Conditions — apply the standard permit conditions and add any special conditions.',
          'Payment — review the payment on file, update the method, or re-vault the card.',
          'Site visit / Inspections — choose how the site is verified and schedule the inspection.',
          'Move through the steps using the wizard’s step nav; complete the final step to approve and issue the permit.',
        ],
      },
    ],
  },
  {
    id: 'search',
    title: 'Search applications',
    tagline: 'Find any application, current or historical (Search menu)',
    intro:
      'The Search group finds records across the system. Search Applications covers everything in the online system; the History screens cover paper-era permits and wells; and Cancelled Applications lists applications withdrawn before approval. A 13-digit Application ID opens that application’s detail page directly.',
    cta: { to: '/search', label: 'Open Search' },
    steps: [
      {
        title: 'Search Applications',
        image: 'search-01-results.png',
        alt: 'Search Applications form with grouped fields and a results table below',
        description:
          'Purpose: the primary application search — find any online-system application using any combination of application, project, applicant, wells, and driller criteria.',
        instructions: [
          'Fill in any fields across the Application, Project, Applicant, Wells, and Driller sections — you can combine several.',
          'Click Search to run the query, or Clear to reset the form.',
          'Results appear in the table below; click a column header to sort or an Application ID to open its detail page.',
          'Entering a full 13-digit Application ID and searching opens that application directly.',
        ],
      },
      {
        title: 'History Permits (1987–April 2005)',
        image: 'search-02-history-permits.png',
        alt: 'Pre-System History Permits search form and results table',
        description:
          'Purpose: look up permits issued on paper before the online system, kept in the legacy history permits table.',
        instructions: [
          'Search by Permit #, Work Type, Well Completion Report #, address, city, consultant, driller, or a permit / start date or year.',
          'Click Search; click a Permit # in the results to open its full detail page.',
          'Use “Add History” to record a new pre-system permit, or open a permit to edit or delete it.',
        ],
      },
      {
        title: 'History Well Locations',
        image: 'search-03-history-wells.png',
        alt: 'History Well Locations search form and results table',
        description:
          'Purpose: find historical well locations (from the legacy well-location table) by tract, section, address, or owner.',
        instructions: [
          'Fill any of Permit #, Tract #, Section #, street address, city, owner name, or well use, then Search.',
          'Click a Tract – Section link to open that well’s detail page.',
          'Use “Add History Well Location” to record a new legacy well location.',
        ],
      },
      {
        title: 'Cancelled Applications',
        image: 'search-04-cancelled.png',
        alt: 'Cancelled Applications search form and results table with Cancelled status pills',
        description:
          'Purpose: review applications that were cancelled before approval (status “Cancelled”).',
        instructions: [
          'Filter by applicant business, last / first name, application ID, email, or date applied, then Search.',
          'Click an Application ID to open the cancelled application and review its history.',
        ],
      },
    ],
  },
  {
    id: 'inspections',
    title: 'Inspections',
    tagline: 'Pending lists, holds, and the scheduling calendar (Inspections menu)',
    intro:
      'The Inspections group tracks permits through the field-inspection process. Inspections List holds permits pending a site inspection; Pending WCR and Pending GeoLog track outstanding completion documents; Permits On Hold lists permits an inspector has paused; and the Inspections Calendar shows what is scheduled by day.',
    cta: { to: '/inspections/list', label: 'Open Inspections List' },
    steps: [
      {
        title: 'Inspections List',
        image: 'inspections-01-list.png',
        alt: 'Inspections list with a date/inspector filter and a table of permits pending inspection',
        description:
          'Purpose: find and schedule permits that still need a field inspection.',
        instructions: [
          'Filter by Inspection Date or Inspector, then click Refresh List.',
          'Each row shows the permit range, contractor, project site, project dates, and current schedule.',
          'Use Update / Add to schedule or edit an inspection, Print Permit to open the printable permit, or Open for the full application.',
        ],
      },
      {
        title: 'Pending WCR List',
        image: 'inspections-03-pending-wcr.png',
        alt: 'Pending WCR list of permits awaiting a Well Completion Report',
        description:
          'Purpose: track permits awaiting a Well Completion Report (WCR).',
        instructions: [
          'Filter by Inspector or Application Id, then click Refresh List.',
          'Click the Application Id link to open the detail page and enter the WCR for that permit.',
        ],
      },
      {
        title: 'Pending GeoLog List',
        image: 'inspections-04-pending-geolog.png',
        alt: 'Pending GeoLog list of permits awaiting a geotechnical log',
        description:
          'Purpose: track permits awaiting a geotechnical log (GeoLog).',
        instructions: [
          'Filter by Inspector or Application Id, then click Refresh List.',
          'Click the Application Id link to open the detail page and upload the GeoLog.',
        ],
      },
      {
        title: 'Permits On Hold List',
        image: 'inspections-05-hold.png',
        alt: 'Permits on hold list filtered by inspector',
        description:
          'Purpose: list permits an inspector has placed on hold so they can be reviewed and released.',
        instructions: [
          'Filter by Inspector, then click Refresh List.',
          'Use “Update Permit Status” on a row to take the permit off hold or record the reason it is held.',
        ],
      },
      {
        title: 'Inspections Calendar',
        anchor: 'inspections-calendar',
        image: 'inspections-02-calendar.png',
        alt: 'Monthly inspections calendar with day cells showing scheduled inspection counts',
        description:
          'Purpose: see scheduled inspections at a glance and plan the day.',
        instructions: [
          'Use the ‹‹ and ›› buttons to move between months.',
          'Days with scheduled inspections show a count badge.',
          'Click a day to list that day’s assignments (application, inspector, time, and status) in the side panel.',
        ],
      },
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    tagline: 'Operational summaries and data extracts',
    intro:
      'The Reports hub gathers the operational reports: reconciliation, completed work, completed inspections, an Excel extract, and any configured SSRS reports.',
    cta: { to: '/reports', label: 'Open Reports' },
    steps: [
      {
        title: 'Choose a report',
        image: 'reports-01-hub.png',
        alt: 'Reports hub with cards for reconciliation, completed work, completed inspections, and extract',
        description: 'Pick the report you need from the hub.',
        instructions: [
          'Reconciliation — paid transactions in a date range, grouped by payment method.',
          'Completed Work / Completed Inspections — closed permits and inspections grouped by inspector.',
          'Extract to Excel — a flat permit/well extract with CSV export.',
          'SSRS reports appear here when a report server is configured for the environment.',
        ],
      },
    ],
  },
  {
    id: 'maintenance',
    title: 'Code Maintenance',
    tagline: 'Reference / lookup code tables',
    intro:
      'Code Maintenance is where staff maintain the reference (lookup) codes used throughout the application and approval workflow. The menu groups the tables into Location Codes, Work Setup, Conditions, Reference Codes, and Inspections. Changing a code here changes the choices applicants and staff see across both portals, so edit with care.',
    cta: { to: '/maintenance', label: 'Open Code Maintenance' },
    steps: [
      {
        title: 'Choose a code table',
        image: 'maintenance-01-menu.png',
        alt: 'Code Maintenance menu with grouped tiles for each reference table',
        description:
          'Purpose: a single hub linking to every editable reference table — cities and states, work categories / types, well uses, drilling methods, permit conditions, payment / status / document types, and inspector setup.',
        instructions: [
          'Pick a tile to open that table’s list screen.',
          'On a list screen use Add to create a new code, or open a row to edit it.',
          'Where a code is in use it is deactivated (Active = N) rather than deleted, so historical records keep their meaning.',
        ],
      },
    ],
  },
];

export { helpSections, IMG as HELP_IMG_BASE };
