// Content for the public Help & How-To guide. Kept as data so the Help page can render, filter
// (search), and deep-link to each section. Screenshots live in public/help/ecomm and are
// (re)generated by e2e/capture-help.spec.js (`npm run capture:help`).

const IMG = `${process.env.PUBLIC_URL}/help/ecomm`;

const helpSections = [
  {
    id: 'overview',
    title: 'Getting started',
    tagline: 'What you can do in this portal',
    intro:
      'The Alameda County Public Works Well Permit portal lets members of the public apply for a new well permit, upload a required site map, and track an application status online — no account or login required.',
    steps: [
      {
        title: 'Three things you can do',
        description:
          'Use the navigation bar at the top of every page to move between the main tasks.',
        instructions: [
          'Apply — complete the guided application wizard and pay your permit fee.',
          'Track Status — look up an application you already submitted and see where it stands.',
          'Upload a site map — attach the required site-map file to an application that is waiting for one.',
        ],
      },
      {
        title: 'Before you begin',
        description: 'Have this information ready so you can finish the application in one sitting.',
        instructions: [
          'Applicant contact information (business name, address, phone, and email).',
          'The project location and expected construction start / completion dates.',
          'Driller name, license number, and well specifications.',
          'Your site-map file, ready to upload (Adobe PDF preferred).',
          'A payment method: credit card, check, or a fee-exemption code.',
        ],
      },
    ],
  },
  {
    id: 'apply',
    title: 'Apply for a well permit',
    tagline: 'A guided, seven-step wizard',
    intro:
      'Applying is a step-by-step wizard. Fill in each step and click Continue. The progress bar at the top shows where you are — you can click any completed step to jump back and change it. Required fields are marked with a red asterisk (*).',
    cta: { to: '/apply', label: 'Start an application' },
    steps: [
      {
        title: 'Step 1 — Project location',
        image: 'apply-01-location.png',
        alt: 'Apply wizard, Project Location step with a map and address fields',
        description: 'Tell us where the well work will take place.',
        instructions: [
          'Type an address in the “Search Address” box, or click directly on the map, to drop a marker.',
          'The map fills in the Location Address / Description automatically — add any extra detail (200 characters max).',
          'Choose the Location City from the list.',
          'The Lat / Long is set from the marker; you do not need to type coordinates.',
        ],
      },
      {
        title: 'Step 2 — Applicant',
        image: 'apply-02-applicant.png',
        alt: 'Apply wizard, Applicant step with business and contact fields',
        description: 'Enter who is applying for the permit.',
        instructions: [
          'Provide the applicant business name and the contact person’s first and last name.',
          'Enter the mailing address, phone number, and a valid email address (used for all notifications).',
          'Optionally add CC email addresses to copy others on status emails.',
        ],
      },
      {
        title: 'Step 3 — Project details',
        image: 'apply-03-project.png',
        alt: 'Apply wizard, Project step with dates, hazards, and property owner fields',
        description: 'Set the project dates and the property owner.',
        instructions: [
          'Pick the construction Start and Completion dates from the availability calendar (weekdays only, roughly 10–90 days out, excluding county holidays).',
          'Indicate whether the site has known hazards — if you choose Yes, an extra “Site Hazard” step is added to the wizard.',
          'Enter the property owner’s name and address (or mark the client the same as the owner).',
        ],
      },
      {
        title: 'Step 4 — Work type',
        image: 'apply-04-worktype.png',
        alt: 'Apply wizard, Work Type step with category and type selection',
        description: 'Choose the kind of work you are permitting.',
        instructions: [
          'Select a work Category (for example, Construction).',
          'Select the specific Work Type within that category.',
          'The permit fee is calculated automatically from your selection.',
        ],
      },
      {
        title: 'Step 5 — Work information',
        image: 'apply-05-workinfo.png',
        alt: 'Apply wizard, Work Info step with driller details and a well specifications table',
        description: 'Provide the driller and the well specifications.',
        instructions: [
          'Choose the Well Use, and enter the Driller Name, Driller License #, and Drilling Method.',
          'Add one row per well in the Wells Specifications table (owner well id, hole & casing diameter, seal & max depth).',
          'Use “Pin Wells on Map” to set each well’s coordinates.',
          'Click “+ Add Well” to add more wells, or “Remove” to delete a row.',
        ],
      },
      {
        title: 'Step 6 — Payment',
        image: 'apply-06-payment.png',
        alt: 'Apply wizard, Payment step with payment-type options',
        description: 'Choose how you will pay the permit fee.',
        instructions: [
          'Select a payment type: Credit Card, Check, or Fee Exemption.',
          'For Check, enter the name on the account.',
          'For a Fee Exemption, enter the exemption code provided by the County.',
        ],
      },
      {
        title: 'Step 7 — Review & submit',
        image: 'apply-07-verify.png',
        alt: 'Apply wizard, Verify step showing a full application summary and Submit button',
        description: 'Check everything, then submit.',
        instructions: [
          'Review each section of the summary carefully.',
          'Use the Edit button on any section to go back and correct it.',
          'Click “Submit Application” (or “Pay Now and Submit” for a credit card) to finish.',
          'You’ll receive a confirmation page and email with your Application ID — keep it to track your application.',
        ],
      },
      {
        title: 'Paying by credit card — the secure IntelliPay window',
        image: 'apply-08-intellipay.png',
        alt: 'The secure IntelliPay card-entry window opened over the verify page',
        description:
          'If you chose Credit Card, clicking “Pay Now and Submit” records your application and opens a secure IntelliPay window to collect your card. Your card is stored and authorized for $0.00 now — the permit fee is charged only after County staff approves your permit.',
        instructions: [
          'Enter your card number, expiration date, CVV, and billing ZIP code in the secure IntelliPay window.',
          'Complete any on-screen security check if one is shown.',
          'Click “Submit Payment”. Card entry happens entirely inside IntelliPay’s secure window — the County never sees or stores your full card number.',
          'On approval the window closes and you return to the confirmation page with your Application ID; if a card is declined, IntelliPay tells you inside the window so you can try another card.',
        ],
      },
    ],
  },
  {
    id: 'track',
    title: 'Track an application',
    tagline: 'Check the status of a submitted application',
    intro:
      'Use Track Status to find an application you already submitted and see where it is in the review process. No login is required — you look it up with your Application ID and email, or by business, driller, or city.',
    cta: { to: '/track', label: 'Track an application' },
    steps: [
      {
        title: 'Search for your application',
        image: 'track-01-search.png',
        alt: 'Track page search form',
        description: 'Enter what you know and run a lookup.',
        instructions: [
          'Enter your Application ID and the email address used on the application, or',
          'Search by Applicant Business, Driller’s Name, or Project Site City.',
          'Click Search. (A quick, invisible security check runs automatically — you normally won’t notice it.)',
        ],
      },
      {
        title: 'Read your results',
        image: 'track-02-results.png',
        alt: 'Track page results table with several applications and status pills',
        description: 'Review the status of each matching application.',
        instructions: [
          'Each row shows the date applied, Application ID, applicant, project site, driller, and status.',
          'Click any column header to sort; use the pager at the bottom for large result sets.',
          'Status pills tell you the stage: “Pending Approval”, “Pending Sitemap”, “Approved”, and so on.',
          'If a row shows “Pending Sitemap”, an “Upload Sitemap” button appears — see the next section.',
        ],
      },
    ],
  },
  {
    id: 'sitemap',
    title: 'Upload a site map',
    tagline: 'Required before an application can be approved',
    intro:
      'When an application’s status is “Pending Sitemap”, County staff need a site-map file before they can approve it. You can attach that file right from the Track results — no need to re-apply.',
    cta: { to: '/track', label: 'Go to Track to upload' },
    steps: [
      {
        title: 'Attach your site-map file',
        image: 'sitemap-01-upload.png',
        alt: 'Track results row expanded to show the site-map upload panel',
        description: 'Upload the file directly from your search results.',
        instructions: [
          'On the Track page, search for your application and find the row marked “Pending Sitemap”.',
          'Click the “Upload Sitemap” button on that row to open the upload panel.',
          'Click “Choose File” and select your site map (Adobe PDF preferred; PNG, JPG, GIF, and TIFF are also accepted).',
          'Click “Upload Sitemap File”. On success the status changes to “Pending Approval”.',
        ],
      },
    ],
  },
];

export { helpSections, IMG as HELP_IMG_BASE };
